### ISSUE TITLE
Add support for a bar chart of DMS preferences

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#1]

**Comment by skhilton** [comment]
https://www.d3-graph-gallery.com/barplot

**Comment by huddlej** [comment]
[This demo from Mike Bostock](https://observablehq.com/@d3/stacked-bar-chart) has been the most helpful for wrapping my head around the stacking logic. I still need to figure out the best way to map our long data to this type of example based on wide data.
