### ISSUE TITLE
Troubleshoot inability to reference nested data on GitHub pages

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#130]
Data stored in nested directories within the top-level GitHub pages directory cannot be accessed as expected. This means all data and code currently has to live in the top-level directory.

Interestingly, this nesting problem does not occur when testing locally with `http-server`.

**Comment by skhilton** [comment]
just as a reminder, if we figure this out we should update the README

**Comment by huddlej** [comment]
Looking into this more, I wanted to take some notes about what is maybe happening.

1. [GitHub Pages renders sites with Jekyll by default](https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators). This default behavior can be disabled by adding an empty `.nojekyll` file to the top of the repo.
2. [Jekyll excludes all directories that start with a `_` (e.g., `_data`) by default](https://jekyllrb.com/docs/structure/).
3. [Jekyll can be configured with a _config.yml file](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site) to explicitly allow directories like `_data` to be exported from its build process

I tested the idea of explicitly allowing the `_data` directory to be exported with [this commit](https://github.com/dms-view/dms-view.github.io/commit/3d16a91455176e305cb0d1dd9ec8c3b117732a9b) and [it worked](https://dms-view.github.io/_data/).

However, it might be clearest for future maintainers to merge the docs repo with this repo and continue to serve the docs with Jekyll even though the main app is not using Jekyll. Since we don't actually use the `_data` and `_javascript` directories as they are designed for Jekyll, maybe we can move our data and source code into `data` and `javascript` directories (no leading underscores) to get around this Jekyll issue completely.

**Comment by skhilton** [comment]
@huddlej: Was this fixed by #167?

**Comment by huddlej** [comment]
@skhilton Yep! Closing now.
