### ISSUE TITLE
Add logoplots for the `mutation_` metrics

### ISSUE THREAD

**Issue by skhilton** [dms-view/dms-view.github.io#15]
Maybe following this [stackoverflow comment ](https://stackoverflow.com/questions/14341800/drawing-sequence-logos-in-d3)

**Comment by huddlej** [comment]
We might be able to use [opentype.js](https://github.com/opentypejs/opentype.js) to avoid defining our own glyph paths. In particular, the API function `charToGlyph` seems promising, if we can convert amino acid letters to glyphs and transform those as needed.
