### ISSUE TITLE
JOSS review # 4

### ISSUE THREAD

**Issue by thorvere** [dms-view/dms-view.github.io#150]
This issue is raised in context of the review process for JOSS:

It is really nice that the tool gives the possibility to add pdbs with different chains, enabling the visualization of sites in the context of protein interaction surfaces. But this fact is not really mentioned in the documentation, which is a pity (especially considering that the documentation example is actually the HA homotrimer). 
In this regard a different background color for the different chains would be helpful to actually easily see that what the user looks at is a multimeric molecule.

**Comment by skhilton** [comment]
> It is really nice that the tool gives the possibility to add pdbs with different chains, enabling the visualization of sites in the context of protein interaction surfaces. But this fact is not really mentioned in the documentation, which is a pity (especially considering that the documentation example is actually the HA homotrimer).

Thank you for catching this gap in our documentation, @thorvere! We’ve added a [section to the documentation](https://github.com/dms-view/dms-view.github.io/blame/dc8e3c6/docs/dataupload.md#L71-L72) to discuss the flexibility specifying a PDB file, such as displaying a multimeric protein, to address this point.

> In this regard a different background color for the different chains would be helpful to actually easily see that what the user looks at is a multimeric molecule.

We agree this would be a helpful feature, especially to differentiate between different proteins in a single view (enzyme/ligand, viral protein/antibody, etc), and we have investigated what would be required to implement this in dms-view. Unfortunately, the flexibility that makes PDB a powerful format also makes implementation of custom chain colors technically challenging. Chains in a PDB file can represent a whole multimeric protein, a single monomer of a multimeric protein, or even a single domain of a monomer. Furthermore, some multimeric proteins are a single chain/monomer in the PDB file with information on how to “mirror” the monomers. Handling _all_ potential color schemes robustly will not be trivial and will require users to maintain a new PDB metadata file. 

However, we thought we could implement a feature where the protein is colored by whether or not the chain is in the data file or not (two colors). We are working on this feature in PR #171. @thorvere, do the ideas we outline there address your concerns?

**Comment by thorvere** [comment]
Hi, 
yes that serves the purpose and makes it way easier to look at the data. So the point is adressed
