### ISSUE TITLE
Example PDB file

### ISSUE THREAD

**Issue by afrubin** [dms-view/dms-view.github.io#159]
I wasn't able to find a link to the PDB record in the example documentation or the paper. After consulting the methods for [Lee et al. 2019](https://elifesciences.org/articles/49324) I see now that the "4O5N" in the file name is the PDB accession number.

This should be made more explicit in the example documentation and the authors should consider citing [Lee et al. 2014](https://www.nature.com/articles/ncomms4614) in the JOSS paper.

**Comment by afrubin** [comment]
Looking into this further, I see that the PDB file used by dms-view is actually a trimer based on the 4O5N structure and not a file from PDB directly. I was going to ask why it wasn't possible to just use a PDB accession number instead of having to provide a full file, but I see now that this is a potentially important feature.

I think it's worth adding a sentence in the paper and/or docs making this explicit (that by providing your own PDB file rather than an accession you can make these sorts of modifications).

**Comment by skhilton** [comment]
@huddlej: when you get a chance can you review the changes here https://github.com/dms-view/docs/pull/15

**Comment by huddlej** [comment]
Thank you, @afrubin! This issue has been resolved by https://github.com/dms-view/docs/pull/15.
