### ISSUE TITLE
clarify status of `dms-view/docs` repo

### ISSUE THREAD

**Issue by jbloom** [dms-view/dms-view.github.io#176]
I was trying to understand how docs are served. My impression is that they might now be served out of the `./docs/` subdirectory of https://github.com/dms-view/dms-view.github.io rather than out of https://github.com/dms-view/docs?

If this is the case, I think this should be somewhere stated in README, and in particular the README for https://github.com/dms-view/docs should say that it is not used and is just being kept for legacy purposes (if it's not deleted altogether).

**Comment by skhilton** [comment]
@jbloom: The docs are now being served out of `dms-view/dms-view.github.io/docs` I will update the README in `dms-view/docs` but we did archive that repo is it is technically read-only. I want to keep it around a little while longer just to make sure we don't need anything from its history.

**Comment by skhilton** [comment]
This is closed by dms-view/docs@ab5818ec.
