### ISSUE TITLE
Settle on a final PDB viewer with expected upload behavior

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#2]

**Comment by skhilton** [comment]
Here are some alternative protein viewers we could consider using. 

1. [PV](https://biasmv.github.io/pv/). [demo](https://biasmv.github.io/pv/demo.html). [github](https://github.com/biasmv/pv). Pros: javascript, seems fast and light weight. Cons: There are not many examples. Specifically, there are not any examples of selecting a small subset of sites. 

2. [nglview](https://github.com/arose/nglview). Pros: Jesse used it for Juhye's last paper. Cons: I think it might just be for jupyter notebooks? 

3. [JSmol](http://jmol.sourceforge.net/). [documentation](https://chemapps.stolaf.edu/jmol/docs/). [example](https://chemapps.stolaf.edu/jmol/jsmol/jsmol.htm). Pros: Uses JS, used by many people. Cons: has a lot of features we don't necessarily want.

**Comment by huddlej** [comment]
PV is no longer maintained, but the JS library behind the nglview Jupyter extension, [ngl](http://nglviewer.org/ngl/api/index.html), looks actively maintained and is documented better than JSmol. Maybe we could play with this today?
