### ISSUE TITLE
Sort residues in logo plots by metric value

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#38]

**Comment by skhilton** [comment]
@huddlej: This is what we are looking for!
https://stackoverflow.com/questions/25253834/sorting-a-d3-js-stacked-bar-chart

**Comment by huddlej** [comment]
I think you're right. d3.stack doesn't support independent sorting of columns, but it seems simpler (maybe?) to calculate our own y offsets for the stacks. The following line of code gets pretty close to the format we need to send to d3:

```
// You can paste this into the inspector console on the dropdown-menu branch.
Array.from(d3.groups(punchCard.data.sort((a, b) => (a["metric"] > b["metric"] ? 1 : (a["metric"] < b["metric"] ? -1 : 0))), d => d["site"]).values())
```

This is sorting by metric across all records and then grouping by site. d3 maintains the relative order of the nested records, so residues end up properly sorted by site. The last bit to add to this is the calculation of the initial and final y offsets for the letters. I'll give this a shot and post an update here.
