### ISSUE TITLE
Add a toggle to switch between multiple datasets in the line plot

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#5]

**Comment by skhilton** [comment]
also look at radio buttons and/or checkboxes

**Comment by skhilton** [comment]
Here is an example of a dropdown menu:
http://bl.ocks.org/williaster/10ef968ccfdc71c30ef8

**Comment by skhilton** [comment]
https://www.d3-graph-gallery.com/graph/line_change_data.html

**Comment by skhilton** [comment]
implemented by commit a37cc0d3e1e74b (I think)
