### ISSUE TITLE
Enable brushing and shift-clicking to select multiple sites in the line plot

### ISSUE THREAD

**Issue by huddlej** [dms-view/dms-view.github.io#8]

**Comment by skhilton** [comment]
The following resources have been helpful when working on this issue: 

https://www.d3-graph-gallery.com/graph/interactivity_brush.html

http://wrobstory.github.io/2013/11/D3-brush-and-tooltip.html

The second link has an example of a clear button if we would like to implement that later

**Comment by skhilton** [comment]
Here is how to select nodes and loop over them. This will be helpful for filling in the color of the brushed nodes.

https://stackoverflow.com/questions/27405377/iterate-over-already-created-nodes-in-d3js
